import type { Vehicle, Testimonial, NewsArticle } from "./types"

export const vehicles: Vehicle[] = [
  {
    id: "byd-tang-l",
    name: "BYD Tang L",
    brand: "BYD",
    model: "Tang L",
    year: 2025,
    price: 2800000,
    priceDisplay: "ETB 2,800,000",
    images: [
      "/vehicles/byd-tang-l-front.jpg",
      "/vehicles/byd-tang-l-interior.jpg",
      "/vehicles/byd-tang-l-side.jpg",
      "/vehicles/byd-tang-l-rear.jpg",
    ],
    heroImage: "/vehicles/byd-tang-l-hero.jpg",
    range: "600 km",
    acceleration: "4.6s 0-100km/h",
    topSpeed: "190 km/h",
    batteryCapacity: "108.8 kWh",
    chargingTime: "30 min (30-80%)",
    seatingCapacity: 7,
    driveType: "AWD",
    highlights: [
      "Premium 7-seater luxury SUV",
      "Blade Battery technology for maximum safety",
      "DiPilot intelligent driving assistance",
      "15.6-inch rotating touchscreen",
      "Panoramic sunroof",
    ],
    whyEthiopia: [
      "Perfect for large Ethiopian families with 7-seat configuration",
      "600km range ideal for intercity travel across Ethiopia",
      "High ground clearance for Ethiopian road conditions",
      "Luxurious interior befitting Ethiopian hospitality culture",
    ],
    colors: [
      { name: "Cosmos Black", hex: "#0a0a0a" },
      { name: "Arctic White", hex: "#f5f5f5" },
      { name: "Titanium Grey", hex: "#4a4a4a" },
      { name: "Aurora Blue", hex: "#1e3a5f" },
    ],
    features: [
      "NFC digital key",
      "Dynaudio premium sound system",
      "Wireless phone charging",
      "360° camera system",
      "Heat pump AC system",
      "Vehicle-to-Load (V2L) capability",
    ],
    description:
      "The BYD Tang L represents the pinnacle of electric luxury SUVs. With its revolutionary Blade Battery technology and spacious 7-seat configuration, it's the perfect vehicle for discerning Ethiopian families who demand excellence.",
    available: true,
  },
  {
    id: "byd-song-plus",
    name: "BYD Song Plus",
    brand: "BYD",
    model: "Song Plus",
    year: 2025,
    price: 1950000,
    priceDisplay: "ETB 1,950,000",
    images: [
      "/vehicles/byd-song-plus-front.jpg",
      "/vehicles/byd-song-plus-interior.jpg",
      "/vehicles/byd-song-plus-side.jpg",
      "/vehicles/byd-song-plus-rear.jpg",
    ],
    heroImage: "/vehicles/byd-song-plus-hero.jpg",
    range: "505 km",
    acceleration: "5.9s 0-100km/h",
    topSpeed: "175 km/h",
    batteryCapacity: "71.8 kWh",
    chargingTime: "25 min (30-80%)",
    seatingCapacity: 5,
    driveType: "FWD",
    highlights: [
      "Best-selling electric SUV globally",
      "Dragon Face 3.0 design language",
      "Intelligent voice assistant",
      "12.8-inch adaptive rotating screen",
      "DiLink intelligent system",
    ],
    whyEthiopia: [
      "Optimal balance of range and efficiency for daily Addis commute",
      "Compact SUV perfect for city driving and parking",
      "Excellent value proposition for growing middle class",
      "Proven reliability with global sales leadership",
    ],
    colors: [
      { name: "Crystal White", hex: "#ffffff" },
      { name: "Sky Blue", hex: "#87ceeb" },
      { name: "Forest Green", hex: "#228b22" },
      { name: "Rose Gold", hex: "#b76e79" },
    ],
    features: [
      "Remote vehicle control via app",
      "Intelligent navigation",
      "Multiple drive modes",
      "Regenerative braking",
      "LED ambient lighting",
      "Panoramic glass roof",
    ],
    description:
      "The BYD Song Plus combines efficiency with elegance. As one of the world's best-selling electric vehicles, it offers proven technology and exceptional value for Ethiopian drivers seeking a modern, eco-friendly lifestyle.",
    available: true,
  },
  {
    id: "geely-galaxy-e5",
    name: "Geely Galaxy E5",
    brand: "Geely",
    model: "Galaxy E5",
    year: 2025,
    price: 2200000,
    priceDisplay: "ETB 2,200,000",
    images: [
      "/vehicles/geely-galaxy-e5-front.jpg",
      "/vehicles/geely-galaxy-e5-interior.jpg",
      "/vehicles/geely-galaxy-e5-side.jpg",
      "/vehicles/geely-galaxy-e5-rear.jpg",
    ],
    heroImage: "/vehicles/geely-galaxy-e5-hero.jpg",
    range: "550 km",
    acceleration: "5.0s 0-100km/h",
    topSpeed: "185 km/h",
    batteryCapacity: "76 kWh",
    chargingTime: "28 min (30-80%)",
    seatingCapacity: 5,
    driveType: "AWD",
    highlights: [
      "Galaxy OS smart cockpit",
      "10-in-1 electric drive system",
      "Aegis short blade battery",
      "Advanced driver assistance (ADAS)",
      "Sustainable interior materials",
    ],
    whyEthiopia: [
      "AWD system handles Ethiopia's diverse terrain",
      "Galaxy OS supports multiple languages",
      "Sustainable materials align with Ethiopia's green initiatives",
      "Competitive pricing in the premium segment",
    ],
    colors: [
      { name: "Stellar Silver", hex: "#c0c0c0" },
      { name: "Nebula Blue", hex: "#191970" },
      { name: "Cosmic Black", hex: "#1a1a2e" },
      { name: "Moon White", hex: "#f8f8ff" },
    ],
    features: [
      "Face recognition entry",
      "8155 smart cockpit chip",
      "25-speaker sound system",
      "AR head-up display",
      "Wireless charging pad",
      "Smart air purification",
    ],
    description:
      "The Geely Galaxy E5 represents the future of mobility. With its cutting-edge Galaxy OS and innovative safety features, it offers Ethiopian drivers a glimpse into tomorrow's transportation today.",
    available: true,
  },
  {
    id: "toyota-bz3x",
    name: "Toyota BZ3X",
    brand: "Toyota",
    model: "BZ3X",
    year: 2025,
    price: 2500000,
    priceDisplay: "ETB 2,500,000",
    images: [
      "/vehicles/toyota-bz3x-front.jpg",
      "/vehicles/toyota-bz3x-interior.jpg",
      "/vehicles/toyota-bz3x-side.jpg",
      "/vehicles/toyota-bz3x-rear.jpg",
    ],
    heroImage: "/vehicles/toyota-bz3x-hero.jpg",
    range: "520 km",
    acceleration: "6.2s 0-100km/h",
    topSpeed: "160 km/h",
    batteryCapacity: "72.8 kWh",
    chargingTime: "30 min (10-80%)",
    seatingCapacity: 5,
    driveType: "AWD",
    highlights: [
      "Toyota legendary reliability in EV form",
      "e-TNGA platform architecture",
      "Toyota Safety Sense 3.0",
      "Yoke-style steering option",
      "Solar roof panel option",
    ],
    whyEthiopia: [
      "Toyota brand trust well-established in Ethiopia",
      "Extensive service network ready for EVs",
      "Proven durability for Ethiopian conditions",
      "Resale value confidence",
    ],
    colors: [
      { name: "Precious White", hex: "#f5f5dc" },
      { name: "Sonic Blue", hex: "#0066cc" },
      { name: "Black Metallic", hex: "#1c1c1c" },
      { name: "Emotional Red", hex: "#cc0000" },
    ],
    features: [
      "Bi-directional charging",
      "Digital key via smartphone",
      "JBL premium audio",
      "Heated/ventilated seats",
      "Hands-free power tailgate",
      "Toyota Connect services",
    ],
    description:
      "The Toyota BZ3X brings Toyota's legendary reliability to the electric age. For Ethiopian drivers who trust the Toyota name, this SUV delivers familiar quality with zero-emission innovation.",
    available: true,
  },
  {
    id: "geely-starwish",
    name: "Geely Starwish",
    brand: "Geely",
    model: "Starwish",
    year: 2025,
    price: 3200000,
    priceDisplay: "ETB 3,200,000",
    images: [
      "/vehicles/geely-starwish-front.jpg",
      "/vehicles/geely-starwish-interior.jpg",
      "/vehicles/geely-starwish-side.jpg",
      "/vehicles/geely-starwish-rear.jpg",
    ],
    heroImage: "/vehicles/geely-starwish-hero.jpg",
    range: "480 km",
    acceleration: "7.5s 0-100km/h",
    topSpeed: "170 km/h",
    batteryCapacity: "100 kWh",
    chargingTime: "35 min (30-80%)",
    seatingCapacity: 7,
    driveType: "FWD",
    highlights: [
      "Executive-class luxury MPV",
      "Captain seats with massage function",
      "Privacy glass and curtains",
      "Built-in refrigerator",
      "Executive work table",
    ],
    whyEthiopia: [
      "Perfect for Ethiopian business executives",
      "Ideal for VIP transport services",
      "Spacious for extended family gatherings",
      "Ultimate comfort for long-distance travel",
    ],
    colors: [
      { name: "Executive Black", hex: "#0d0d0d" },
      { name: "Pearl White", hex: "#fdfdf5" },
      { name: "Champagne Gold", hex: "#f7e7ce" },
      { name: "Deep Blue", hex: "#00008b" },
    ],
    features: [
      "Zero-gravity captain seats",
      "Rear entertainment system",
      "Ambient fragrance system",
      "Executive privacy partition",
      "Wireless CarPlay/Android Auto",
      "Power sliding doors",
    ],
    description:
      "The Geely Starwish is the ultimate executive MPV. Designed for those who demand the finest, it offers first-class comfort and technology for Ethiopian business leaders and discerning families.",
    available: true,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Yohannes Tadesse",
    role: "CEO",
    company: "Tadesse Holdings",
    content:
      "Kairos Addis made my transition to electric seamless. The BYD Tang L has exceeded all my expectations - from the range to the luxury features. Their service team is exceptional.",
    rating: 5,
    avatar: "/testimonials/customer-1.jpg",
    vehicle: "BYD Tang L",
  },
  {
    id: "2",
    name: "Sara Bekele",
    role: "Medical Director",
    company: "Bekele Medical Center",
    content:
      "As a busy professional, I needed a reliable vehicle. The Toyota BZ3X from Kairos Addis delivers Toyota quality in an eco-friendly package. The 5-year warranty gives me peace of mind.",
    rating: 5,
    avatar: "/testimonials/customer-2.jpg",
    vehicle: "Toyota BZ3X",
  },
  {
    id: "3",
    name: "Abebe Negash",
    role: "Entrepreneur",
    content:
      "The order tracking system kept me informed every step of the way. From payment to delivery, I knew exactly where my Geely Galaxy E5 was. Outstanding customer experience.",
    rating: 5,
    avatar: "/testimonials/customer-3.jpg",
    vehicle: "Geely Galaxy E5",
  },
  {
    id: "4",
    name: "Tigist Hailu",
    role: "Real Estate Developer",
    content:
      "I was skeptical about EVs in Ethiopia, but Kairos Addis addressed all my concerns. The charging solutions and after-sales support have been remarkable. Highly recommended.",
    rating: 5,
    avatar: "/testimonials/customer-4.jpg",
    vehicle: "BYD Song Plus",
  },
]

export const newsArticles: NewsArticle[] = [
  {
    id: "1",
    title: "The Rise of Electric Vehicles in Ethiopia: A Green Revolution",
    slug: "rise-of-evs-in-ethiopia",
    excerpt:
      "Ethiopia is embracing electric mobility as part of its commitment to sustainable development. Learn how EVs are transforming transportation in the country.",
    content: "Full article content here...",
    image: "/news/ev-revolution.jpg",
    category: "ev-benefits",
    author: "Kairos Addis Editorial",
    publishedAt: "2025-01-15",
    readTime: 5,
  },
  {
    id: "2",
    title: "Charging Your EV in Addis Ababa: A Complete Guide",
    slug: "ev-charging-guide-addis",
    excerpt:
      "Everything you need to know about charging your electric vehicle in Ethiopia's capital city, from home charging to public stations.",
    content: "Full article content here...",
    image: "/news/charging-guide.jpg",
    category: "charging",
    author: "Technical Team",
    publishedAt: "2025-01-10",
    readTime: 7,
  },
  {
    id: "3",
    title: "BYD Tang L: The Ultimate Family SUV for Ethiopian Roads",
    slug: "byd-tang-l-review",
    excerpt:
      "An in-depth look at why the BYD Tang L has become the preferred choice for Ethiopian families seeking luxury and sustainability.",
    content: "Full article content here...",
    image: "/news/byd-tang-review.jpg",
    category: "model-highlights",
    author: "Automotive Expert",
    publishedAt: "2025-01-05",
    readTime: 6,
  },
  {
    id: "4",
    title: "Kairos Addis Partners with YouGuard for Extended Warranty Coverage",
    slug: "youguard-partnership-announcement",
    excerpt:
      "We're excited to announce our partnership with YouGuard, bringing industry-leading warranty protection to all our customers.",
    content: "Full article content here...",
    image: "/news/partnership.jpg",
    category: "company-news",
    author: "Kairos Addis",
    publishedAt: "2025-01-01",
    readTime: 3,
  },
]

export const partners = [
  { name: "BYD", logo: "/partners/byd-logo.jpg" },
  { name: "Geely", logo: "/partners/geely-logo.jpg" },
  { name: "Toyota", logo: "/partners/toyota-logo.jpg" },
  { name: "YouGuard", logo: "/partners/youguard-logo.jpg" },
]
